<?php 
/**
 * This class has been autogenerated by RocketPHP
 */

namespace Resources;

class Blogs {

	protected $db;
	protected $fields = array("name","description","posts","owner","created","updated");
	protected static $notExposed = array("");

	function __construct($db){
		$this->db = $db;
	}

	protected function getDataForQuery($query, $data){
		$queryData = array();
		preg_match_all('/:([a-zA-Z0-9_]+)/im', $query, $matches, PREG_SET_ORDER);
		if (count($matches)){
			foreach ($matches as $match){
				if (isset($data[$match[1]])){
					$queryData[$match[1]] = $data[$match[1]];
				}
			}
		}
		return $queryData;
	}

	public static function methodIsExposed($method){
		if (in_array($method, static::$notExposed)){
			return false;
		}
		return true;
	}

	function receive_name($value, &$errors) {
		$errors = array_merge($errors, $this->validate_name($value));
		return $value;
	}

	function validate_name($value) {
		$errors = array();
		if (!is_string($value)){ $errors[] = "name.incorrectType.string"; }
		if (strlen($value) > 30){ $errors[] = "name.tooLong"; }
		if (strlen($value) < 3){ $errors[] = "name.tooShort"; }
		return $errors;
	}

	function receive_description($value, &$errors) {
		$errors = array_merge($errors, $this->validate_description($value));
		return $value;
	}

	function validate_description($value) {
		$errors = array();
		if (!is_string($value)){ $errors[] = "description.incorrectType.string"; }
		if (strlen($value) > 400){ $errors[] = "description.tooLong"; }
		return $errors;
	}

	function receive_posts($value, &$errors) {
		$errors = array_merge($errors, $this->validate_posts($value));
		return $value;
	}

	function validate_posts($value) {
		$errors = array();
		return $errors;
	}

	function posts($id) {
		// TODO: return query here so that users can customize result eg. LIMIT, ORDER BY, WHERE x, etc
		$query = "SELECT * FROM Posts WHERE blog_id = :id";
		$statement = $this->db->prepare($query);
		$statement->execute(array('id' => $id));
		$data = $statement->fetchAll(\PDO::FETCH_ASSOC);
		
		// TODO: $data = customHook($data);
		return $data;
	}

	function receive_owner($value, &$errors) {
		$errors = array_merge($errors, $this->validate_owner($value));
		return $value;
	}

	function validate_owner($value) {
		$errors = array();
		return $errors;
	}

	function owner($id) {
		// TODO: return query here so that users can customize result eg. LIMIT, ORDER BY, WHERE x, etc
		$query = "SELECT * FROM User WHERE id = :id";
		$statement = $this->db->prepare($query);
		$statement->execute(array('id' => $id));
		$data = $statement->fetch(\PDO::FETCH_ASSOC);
		
		// TODO: $data = customHook($data);
		return $data;
	}

	function receive_created($value, &$errors) {
		$errors = array_merge($errors, $this->validate_created($value));
		return $value;
	}

	function validate_created($value) {
		$errors = array();
		if (!is_date($value, 'Y-m-d H:i:s')){ $errors[] = "created.incorrectType.datetime"; }
		return $errors;
	}

	function receive_updated($value, &$errors) {
		$errors = array_merge($errors, $this->validate_updated($value));
		return $value;
	}

	function validate_updated($value) {
		$errors = array();
		if (!is_date($value, 'Y-m-d H:i:s')){ $errors[] = "updated.incorrectType.datetime"; }
		return $errors;
	}

	function GET_blogs_when_public($data) {
		$errors = array();

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		if (count($errors)) {
			throw new \InvalidInputDataException($errors);
		}

		\Rocket::call(array("TimeTracked", "on_input"), $data);
		\Rocket::call(array("paginated", "on_input"), $data);
		$query = "SELECT * FROM Blogs";
		\Rocket::call(array("paginated", "on_query"), $query, $data);
		$statement = $this->db->prepare($query);
		$statement->execute( $this->getDataForQuery($query, $data) );
		$data = $statement->fetchAll(\PDO::FETCH_ASSOC);
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		\Rocket::call(array("paginated", "on_data"), $data);
		return $data;
	}

	function POST_blogs_when_public($data) {
		$errors = array();

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		if (count($errors)) {
			throw new \InvalidInputDataException($errors);
		}

		\Rocket::call(array("TimeTracked", "on_input"), $data);
		$fields = array_intersect($this->fields, array_keys($data));
		$query = "INSERT INTO Blogs (".implode(',', $fields).") VALUES (:".implode(', :', $fields).")";
		$statement = $this->db->prepare($query);
		$statement->execute( $this->getDataForQuery($query, $data) );
		$id = $this->db->lastInsertId();
		if (!$id){
			throw new \Exception('Could not create resource');
		}
		$query = "SELECT * FROM Blogs WHERE id = :id LIMIT 1";
		$statement = $this->db->prepare($query);
		$statement->execute(array("id" => $id));
		$data = $statement->fetch(\PDO::FETCH_ASSOC);
		if (!$data){
			throw new \Exception('Could not create resource');
		}
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $data;
	}

	function GET_blogs_id_when_public($data, $id) {
		$errors = array();

		$data["id"] = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		if (count($errors)) {
			throw new \InvalidInputDataException($errors);
		}

		\Rocket::call(array("TimeTracked", "on_input"), $data);
		$query = "SELECT * FROM Blogs WHERE id = :id LIMIT 1";
		$statement = $this->db->prepare($query);
		$statement->execute( $this->getDataForQuery($query, $data) );
		$data = $statement->fetch(\PDO::FETCH_ASSOC);
		if (!$data){
			throw new \NotFoundException();
		}
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $data;
	}

	function PUT_blogs_id_when_public($data, $id) {
		$errors = array();

		$data["id"] = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		if (count($errors)) {
			throw new \InvalidInputDataException($errors);
		}

		\Rocket::call(array("TimeTracked", "on_input"), $data);
		$fields = array_intersect($this->fields, array_keys($data));
		$pairs = array();
		foreach ($fields as $field){
			$pairs[] = $field . " = :" . $field;
		}
		$query = "UPDATE Blogs SET ".implode(', ', $pairs)." WHERE id = :id";
		$statement = $this->db->prepare($query);
		$result = $statement->execute( $this->getDataForQuery($query, $data) );
		if (!$result){
			throw new \Exception('Could not update resource');
		}
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $data;
	}

	function GET_blogs_id_posts_when_public($data, $id) {
		$errors = array();

		$data["id"] = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		if (count($errors)) {
			throw new \InvalidInputDataException($errors);
		}

		\Rocket::call(array("TimeTracked", "on_input"), $data);
		$data = $this->posts($id);
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $data;
	}

	function GET_blogs_id_owner_when_public($data, $id) {
		$errors = array();

		$data["id"] = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		if (count($errors)) {
			throw new \InvalidInputDataException($errors);
		}

		\Rocket::call(array("TimeTracked", "on_input"), $data);
		$data = $this->owner($id);
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $data;
	}

}