<?php 
/**
 * This class has been autogenerated by RocketPHP
 */

namespace Pages;

class Blogs_id extends \Rocket\Site\Page{

	function GET_when_public($data, $id) {
		$errors = array();

		$data->id = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		// check for required input data
		if (!isset($data->name)){ $errors[] = "Blogs_id.name.required"; }

		$data->errors = $errors;
		$ref_0 = "/blogs/$data->id";
		$ref_1 = $data;
		$data->blog = \Rocket::call(array("api", "GET"), $ref_0, $ref_1);
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $this->template->render('blog.php', $data);
	}

	function POST_when_public($data, $id) {
		$errors = array();

		$data->id = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		$data->errors = $errors;
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $this->template->render('blogs.php', $data);
	}

}