<?php 
/**
 * This class has been autogenerated by RocketPHP
 */

namespace Pages;

class Blogs extends \Rocket\Site\Page{

	function GET_when_public($data) {
		$errors = array();

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		$data->errors = $errors;
		$ref_0 = "/blogs";
		$ref_1 = $data;
		$data->blogs = \Rocket::call(array("api", "GET"), $ref_0, $ref_1);
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $this->template->render('blogs.php', $data);
	}

	function POST_when_public($data) {
		$errors = array();

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		$data->errors = $errors;
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $this->template->render('blogs.php', $data);
	}

}