<?php 
/**
 * This class has been autogenerated by RocketPHP
 */

namespace Pages;

class Blogs_id extends \Rocket\Site\Page{

	function GET_when_public($data, $id) {
		$errors = $this->errors;

		$data->id = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		$data->errors = $errors;
		$args = array("/blogs/$data->id", $data);
		$data->blog = \Rocket::callArray(array("api", "GET"), $args);
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $this->template->render('blog.php', $data);
	}

	function POST_when_public($data, $id) {
		$errors = $this->errors;

		$data->id = $id;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		$data->errors = $errors;
		try{
		}catch (\InvalidInputDataException $e){
			$this->errors = $e->errors();
			return $this->system->launch('/blogs/{id}', 'GET', $data);
		}
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		//header('Location: /blogs');
		die('redirect');
	}

}