<?php 
/**
 * This class has been autogenerated by RocketPHP
 */

namespace Pages;

class Blogs extends \Rocket\Site\Page{

	function GET_when_public($data) {
		$errors = $this->errors;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		$data->errors = $errors;
		$args = array("/blogs", $data);
		$data->blogs = \Rocket::callArray(array("api", "GET"), $args);
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		return $this->template->render('blogs.php', $data);
	}

	function POST_when_public($data) {
		$errors = $this->errors;

		\Rocket::call(array("ResponseTime", "on_start"), $data);
		$data->errors = $errors;
		try{
			$args = array("/blogs", $data);
			$data->save = \Rocket::callArray(array("api", "POST"), $args);
		}catch (\InvalidInputDataException $e){
			$this->errors = $e->errors();
			return $this->system->launch('/blogs', 'GET', $data);
		}
		\Rocket::call(array("ResponseTime", "on_data"), $data);
		//header('Location: /blogs');
		die('redirect');
	}

}